name: Lint

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    name: Lint
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm build --filter=./packages/*

      - name: Check
        run: pnpm check
